#!/bin/sh

MYVCO=ixl
MYDISPS="1 2"
MYUSER=dbridgew
MYSYSTEM=drake
#SHELL=/bin/zsh   # look up user's default SHELL

# export SHELL

if [ -f $HOME/.profile ]
then
   . $HOME/.profile
fi

for MYDISP in $MYDISPS
do

ps -fe | grep -v grep | grep ${MYUSER} | grep "Xvnc :${MYDISP} "> /dev/null 2>&1
if [ $? -ne 0 ]
then
   rm -rf /tmp/.X${MYDISP}-lock
   rm -rf /tmp/.X11-unix/X${MYDISP}
   rm -rf /user/${MYUSER}/.vnc/${MYSYSTEM}:${MYDISP}*
   nohup vncserver :${MYDISP} -alwaysshared -geometry 3840x2160  < /dev/null > /dev/null 2>&1
fi

done
